### ISSUE TITLE
StatusCode.UNKNOWN, token not found

### ISSUE THREAD

**Issue by stevennt** [zilliztech/akcio#95]
Hi team,

I tried to run this project and had an error as follows with the token, whereas I have set the tokens and it can be seen in the config object. 

Appreciate for any tip to run this. Thanks.

python3 gradio_demo.py --towhee

![image](https://github.com/zilliztech/akcio/assets/32351181/d27c56a6-e3ff-4eef-8e9c-57fb62d59790)

2023-12-08 10:15:15,782 - 140703044237120 - decorators.py-decorators:88 - WARNING: [__internal_register] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, token not found>

grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "token not found"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:34.160.220.160:443 {grpc_message:"token not found", grpc_status:2, created_time:"2023-12-08T10:15:29.907598478+07:00"}"
>

I printed out the config object it looks like this:

config:  type='RecursiveCharacter' chunk_size=300 splitter_kwargs={} embedding_model='BAAI/bge-base-en' openai_api_key='sk-tdnNgbL----------lkQudP2XntZ' embedding_device=-1 embedding_normalize=True milvus_uri='https://in03-f2-------cf.api.gcp-us-west1.zillizcloud.com' milvus_token='ec22ee0b9cef0daffc401b049--------c8a8061f7f41f27a76276bde1fb469b5' milvus_host=None milvus_port=None milvus_user=None milvus_password=None es_enable=False es_connection_kwargs={'hosts': ['https://127.0.0.1:9200'], 'basic_auth': ('elastic', 'my_password')} token_model='gpt-3.5-turbo' llm_kwargs={'temperature': 0.2, 'max_tokens': 20} openai_model='gpt-3.5-turbo' llm_src='openai'

**Comment by jaelgu** [comment]
This looks like something wrong with the Milvus token.
But are you using the latest akcio? The config structure looks strange. Can you try with the latest code following instructions at README or https://github.com/zilliztech/akcio/wiki/Demo

**Comment by stevennt** [comment]
Token and URI: They are from the Zilliz cloud.

And yes I cloned the latest akcio repo, branch main.

**Comment by jaelgu** [comment]
@stevennt Can you connect to Zilliz Cloud with the uri & token? Try with the following code:
```python
from pymilvus import connections, utility

connections.connect(uri=your_uri, token=your_token)
utility.list_collections()
```

**Comment by jaelgu** [comment]
Reproduced this issue. Working on it now.

**Comment by jaelgu** [comment]
Fixed.

Need to update Towhee cache before retrying:
```
rm -rf ~/.towhee/operators/ann-insert
rm -rf ~/.towhee/operators/ann-search
```
